apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ea4dkdbpd-go 
  janus-idp.io/tekton: ea4dkdbpd-go
  backstage.io/kubernetes-id: ea4dkdbpd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ea4dkdbpd-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml