apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ea4dkdbpd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ea4dkdbpd-go 
  name: ea4dkdbpd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ea4dkdbpd-go 
